def ANDROID_FCM_VERSION = System.getenv('ANDROID_FCM_VERSION') ?: rootProject.hasProperty('ANDROID_FCM_VERSION') ? rootProject.ext.ANDROID_FCM_VERSION : '22.0.0'
buildscript {

    ext {
        ANDROID_GRADLE_TOOLS_VERSION = System.getenv('ANDROID_GRADLE_TOOLS_VERSION') ?: rootProject.hasProperty('ANDROID_GRADLE_TOOLS_VERSION') ? rootProject.ext.ANDROID_GRADLE_TOOLS_VERSION : '8.9.1'
        ANDROID_GOOGLE_SERVICES_VERSION = System.getenv('ANDROID_GOOGLE_SERVICES_VERSION') ?: rootProject.hasProperty('ANDROID_GOOGLE_SERVICES_VERSION') ? rootProject.ext.ANDROID_GOOGLE_SERVICES_VERSION : '4.3.3'
        ext.gradleNumberVersion = ANDROID_GRADLE_TOOLS_VERSION.substring(0, ANDROID_GRADLE_TOOLS_VERSION.lastIndexOf(".")).toFloat()
    }

    repositories {
        jcenter()
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${ANDROID_GRADLE_TOOLS_VERSION}"
        classpath "com.google.gms:google-services:${ANDROID_GOOGLE_SERVICES_VERSION}"
    }
}
dependencies {
    implementation "com.userpilot:userpilot-android:1.4.0"
    implementation "com.google.firebase:firebase-messaging:${ANDROID_FCM_VERSION}"
}
